### ISSUE TITLE
Can't lock vscode-jupyter

### ISSUE THREAD

**Issue by janjagusch** [conda-forge/vscode-jupyter-feedstock#12]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

When trying to `conda-lock` an environment that contains `vscode-jupyter` the lock fails with the following error message:

```
generating lockfile for linux-64
Failed to parse json, Expecting value: line 1 column 1 (char 0)
Could not lock the environment for platform linux-64
    Command: ['/usr/local/Caskroom/miniforge/base/bin/mamba', 'create', '--prefix', '/var/folders/mj/2sx68gpn1bldjjpwtbqs8gfr0000gn/T/tmpgxfaepsn/prefix', '--dry-run', '--json', '--override-channels', '--channel', 'quantco_main', '--channel', 'conda-forge', '--channel', 'nodefaults', 'xeus-python', 'ipython', 'vscode-python', 'vscode-jupyter', 'vscode-icons', 'ipdb', 'ipykernel', 'python=3.8']
    STDOUT:
Encountered problems while solving.
Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by vscode-jupyter-2020.12.1-py36h58fc0a5_1
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xhochy** [comment]
That's not a problem of the feedstock.
